### ISSUE TITLE
Crash with error FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by chihung93** [anitaa1990/PagingLibrary-Sample#2]
I think you forget commit CircleImageView and CustomTextView

```
07-11 12:39:26.967 5858-5858/com.an.paginglibrary.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.an.paginglibrary.sample, PID: 5858
    android.view.InflateException: Binary XML file line #22: Error inflating class com.an.paginglibrary.sample.views.CircleImageView
        at android.view.LayoutInflater.createView(LayoutInflater.java:637)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:418)
        at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
        at com.an.paginglibrary.sample.databinding.FeedItemBinding.inflate(FeedItemBinding.java:127)
        at com.an.paginglibrary.sample.databinding.FeedItemBinding.inflate(FeedItemBinding.java:123)
        at com.an.paginglibrary.sample.adapters.FeedListAdapter.onCreateViewHolder(FeedListAdapter.java:45)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6685)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:15701)
        at android.view.ViewGroup.layout(ViewGroup.java:5041)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15701)
        at android.view.ViewGroup.layout(ViewGroup.java:5041)
        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
        at android.view.View.layout(View.java:15701)
        at android.view.ViewGroup.layout(ViewGroup.java:5041)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15701)
        at android.view.ViewGroup.layout(ViewGroup.java:5041)
        at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
        at android.view.View.layout(View.java:15701)
        at android.view.ViewGroup.layout(ViewGroup.java:5041)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15701)
        at android.view.ViewGroup.layout(ViewGroup.java:5041)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15701)
        at android.view.ViewGroup.layout(ViewGroup.java:5041)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15701)
        at android.view.ViewGroup.layout(ViewGroup.java:5041)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2130)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1887)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1104)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5962)
    	at

```

**Comment by anitaa1990** [comment]
CustomTextView is part of the build.gradle file and the CircleImageView is a custom view that is part of the views package in the app. Not able to reproduce this issue. Let me know when you are facing this

**Comment by sreejith-k** [comment]
i am also facing the same issue. error happening on some devices. the error is happening on 
'FeedItemBinding itemBinding = FeedItemBinding.inflate(layoutInflater, parent, false);' inside FeedListAdapter.

**Comment by chihung93** [comment]
I fix for myself and create PR for your repository. Please check it out. Tks
https://github.com/anitaa1990/PagingLibrary-Sample/pull/8
